import type { LcuChampSelectSession } from './session.js'

/** Session factice pour tester l'UI sans lancer League */
export function createDemoChampSelect(): LcuChampSelectSession {
  return {
    localPlayerCellId: 0,
    timer: { phase: 'BAN_PICK', adjustedTimeLeftInPhase: 42000 },
    bans: {
      myTeamBans: [238, 157],
      theirTeamBans: [555, 64],
    },
    myTeam: [
      {
        cellId: 0,
        championId: 103,
        assignedPosition: 'middle',
        spell1Id: 4,
        spell2Id: 14,
        gameName: 'NissaMain',
        tagLine: 'EUW',
        riotId: 'NissaMain#EUW',
      },
      {
        cellId: 1,
        championId: 86,
        assignedPosition: 'top',
        spell1Id: 4,
        spell2Id: 12,
        gameName: 'TopDiff',
        tagLine: 'EUW',
        riotId: 'TopDiff#EUW',
      },
      {
        cellId: 2,
        championId: 64,
        championPickIntent: 64,
        assignedPosition: 'jungle',
        spell1Id: 4,
        spell2Id: 11,
        gameName: 'LeeEnjoyer',
        tagLine: 'euw',
        riotId: 'LeeEnjoyer#euw',
      },
      {
        cellId: 3,
        championId: 222,
        assignedPosition: 'bottom',
        spell1Id: 4,
        spell2Id: 7,
        gameName: 'JinxOnly',
        tagLine: 'EUW',
        riotId: 'JinxOnly#EUW',
      },
      {
        cellId: 4,
        championId: 412,
        assignedPosition: 'utility',
        spell1Id: 4,
        spell2Id: 14,
        gameName: 'HookMaster',
        tagLine: 'EUW',
        riotId: 'HookMaster#EUW',
      },
    ],
    theirTeam: [
      {
        cellId: 5,
        championId: 238,
        assignedPosition: 'middle',
        spell1Id: 4,
        spell2Id: 14,
        gameName: 'ZedGod',
        tagLine: 'EUW',
        riotId: 'ZedGod#EUW',
      },
      {
        cellId: 6,
        championId: 122,
        assignedPosition: 'top',
        spell1Id: 4,
        spell2Id: 6,
        gameName: 'DunkLord',
        tagLine: 'EUW',
        riotId: 'DunkLord#EUW',
      },
      {
        cellId: 7,
        championId: 234,
        assignedPosition: 'jungle',
        spell1Id: 4,
        spell2Id: 11,
        gameName: 'ViegoOTP',
        tagLine: 'EUW',
        riotId: 'ViegoOTP#EUW',
      },
      {
        cellId: 8,
        championId: 145,
        assignedPosition: 'bottom',
        spell1Id: 4,
        spell2Id: 7,
        gameName: 'KaiSaCarry',
        tagLine: 'EUW',
        riotId: 'KaiSaCarry#EUW',
      },
      {
        cellId: 9,
        championId: 267,
        assignedPosition: 'utility',
        spell1Id: 4,
        spell2Id: 3,
        gameName: 'NamiSup',
        tagLine: 'EUW',
        riotId: 'NamiSup#EUW',
      },
    ],
    actions: [
      [
        { actorCellId: 0, championId: 103, completed: true, type: 'pick', isAllyAction: true },
        { actorCellId: 1, championId: 86, completed: true, type: 'pick', isAllyAction: true },
        { actorCellId: 2, championId: 64, completed: false, type: 'pick', isAllyAction: true },
        { actorCellId: 3, championId: 222, completed: true, type: 'pick', isAllyAction: true },
        { actorCellId: 4, championId: 412, completed: true, type: 'pick', isAllyAction: true },
        { actorCellId: 5, championId: 238, completed: true, type: 'pick', isAllyAction: false },
        { actorCellId: 6, championId: 122, completed: true, type: 'pick', isAllyAction: false },
        { actorCellId: 7, championId: 234, completed: true, type: 'pick', isAllyAction: false },
        { actorCellId: 8, championId: 145, completed: true, type: 'pick', isAllyAction: false },
        { actorCellId: 9, championId: 267, completed: true, type: 'pick', isAllyAction: false },
      ],
    ],
  }
}
